
CREATE PROCEDURE [dbo].[app_Programs_Update] (
	@PID INT,
	@AdminName VARCHAR(50),
	@Title VARCHAR(50),
	@TabName VARCHAR(20),
	@POrder INT,
	@IsActive BIT,
	@IsHidden BIT,
	@StartDate DATETIME,
	@EndDate DATETIME,
	@MaxAge INT,
	@MaxGrade INT,
	@LoggingStart DATETIME,
	@LoggingEnd DATETIME,
	@ParentalConsentFlag BIT,
	@ParentalConsentText TEXT,
	@PatronReviewFlag BIT,
	@LogoutURL VARCHAR(150),
	@ProgramGameID INT,
	@HTML1 TEXT,
	@HTML2 TEXT,
	@HTML3 TEXT,
	@HTML4 TEXT,
	@HTML5 TEXT,
	@HTML6 TEXT,
	@BannerImage VARCHAR(150),
	@RegistrationBadgeID INT,
	@CompletionPoints INT = 0,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@LastModDate DATETIME,
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = '',
	@PreTestID INT = 0,
	@PostTestID INT = 0,
	@PreTestMandatory INT = 0,
	@PretestEndDate DATETIME,
	@PostTestStartDate DATETIME
	)
AS
UPDATE Programs
SET AdminName = @AdminName,
	Title = @Title,
	TabName = @TabName,
	POrder = @POrder,
	IsActive = @IsActive,
	IsHidden = @IsHidden,
	StartDate = @StartDate,
	EndDate = @EndDate,
	MaxAge = @MaxAge,
	MaxGrade = @MaxGrade,
	LoggingStart = @LoggingStart,
	LoggingEnd = @LoggingEnd,
	ParentalConsentFlag = @ParentalConsentFlag,
	ParentalConsentText = @ParentalConsentText,
	PatronReviewFlag = @PatronReviewFlag,
	LogoutURL = @LogoutURL,
	ProgramGameID = @ProgramGameID,
	HTML1 = @HTML1,
	HTML2 = @HTML2,
	HTML3 = @HTML3,
	HTML4 = @HTML4,
	HTML5 = @HTML5,
	HTML6 = @HTML6,
	BannerImage = @BannerImage,
	RegistrationBadgeID = @RegistrationBadgeID,
	CompletionPoints = @CompletionPoints,
	LastModUser = @LastModUser,
	AddedDate = @AddedDate,
	AddedUser = @AddedUser,
	LastModDate = @LastModDate,
	TenID = @TenID,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3,
	PreTestID = @PreTestID,
	PostTestID = @PostTestID,
	PreTestMandatory = @PreTestMandatory,
	PretestEndDate = @PretestEndDate,
	PostTestStartDate = @PostTestStartDate
WHERE PID = @PID
	AND TenID = @TenID
