
CREATE PROCEDURE [dbo].[app_Minigame_Update] (
	@MGID INT,
	@MiniGameType INT,
	@MiniGameTypeName VARCHAR(50),
	@AdminName VARCHAR(50),
	@GameName VARCHAR(50),
	@isActive BIT,
	@NumberPoints INT,
	@AwardedBadgeID INT,
	@Acknowledgements TEXT,
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = ''
	)
AS
UPDATE Minigame
SET MiniGameType = @MiniGameType,
	MiniGameTypeName = @MiniGameTypeName,
	AdminName = @AdminName,
	GameName = @GameName,
	isActive = @isActive,
	NumberPoints = @NumberPoints,
	AwardedBadgeID = @AwardedBadgeID,
	Acknowledgements = @Acknowledgements,
	LastModDate = @LastModDate,
	LastModUser = @LastModUser,
	AddedDate = @AddedDate,
	AddedUser = @AddedUser,
	TenID = @TenID,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3
WHERE MGID = @MGID
	AND TenID = @TenID
