
--Create the Insert Proc
CREATE PROCEDURE [dbo].[app_Tenant_Insert] (
	@Name VARCHAR(150),
	@LandingName VARCHAR(50),
	@AdminName VARCHAR(50),
	@isActiveFlag BIT,
	@isMasterFlag BIT,
	@Description TEXT,
	@DomainName VARCHAR(50),
	@showNotifications BIT,
	@showOffers BIT,
	@showBadges BIT,
	@showEvents BIT,
	@NotificationsMenuText VARCHAR(50),
	@OffersMenuText VARCHAR(50),
	@BadgesMenuText VARCHAR(50),
	@EventsMenuText VARCHAR(50),
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@FldInt1 INT,
	@FldInt2 INT,
	@FldInt3 INT,
	@FldBit1 BIT,
	@FldBit2 BIT,
	@FldBit3 BIT,
	@FldText1 TEXT,
	@FldText2 TEXT,
	@FldText3 TEXT,
	@TenID INT OUTPUT
	)
AS
BEGIN
	INSERT INTO Tenant (
		NAME,
		LandingName,
		AdminName,
		isActiveFlag,
		isMasterFlag,
		Description,
		DomainName,
		showNotifications,
		showOffers,
		showBadges,
		showEvents,
		NotificationsMenuText,
		OffersMenuText,
		BadgesMenuText,
		EventsMenuText,
		LastModDate,
		LastModUser,
		AddedDate,
		AddedUser,
		FldInt1,
		FldInt2,
		FldInt3,
		FldBit1,
		FldBit2,
		FldBit3,
		FldText1,
		FldText2,
		FldText3
		)
	VALUES (
		@Name,
		@LandingName,
		@AdminName,
		@isActiveFlag,
		@isMasterFlag,
		@Description,
		@DomainName,
		@showNotifications,
		@showOffers,
		@showBadges,
		@showEvents,
		@NotificationsMenuText,
		@OffersMenuText,
		@BadgesMenuText,
		@EventsMenuText,
		@LastModDate,
		@LastModUser,
		@AddedDate,
		@AddedUser,
		@FldInt1,
		@FldInt2,
		@FldInt3,
		@FldBit1,
		@FldBit2,
		@FldBit3,
		@FldText1,
		@FldText2,
		@FldText3
		)

	SELECT @TenID = SCOPE_IDENTITY()
END
