
CREATE PROCEDURE [dbo].[app_Patron_Update] (
	@PID INT,
	@IsMasterAccount BIT,
	@MasterAcctPID INT,
	@Username VARCHAR(50),
	@Password VARCHAR(255),
	@DOB DATETIME,
	@Age INT,
	@SchoolGrade VARCHAR(5),
	@ProgID INT,
	@FirstName VARCHAR(50),
	@MiddleName VARCHAR(50),
	@LastName VARCHAR(50),
	@Gender VARCHAR(1),
	@EmailAddress VARCHAR(150),
	@PhoneNumber VARCHAR(20),
	@StreetAddress1 VARCHAR(80),
	@StreetAddress2 VARCHAR(80),
	@City VARCHAR(20),
	@State VARCHAR(2),
	@ZipCode VARCHAR(10),
	@Country VARCHAR(50),
	@County VARCHAR(50),
	@ParentGuardianFirstName VARCHAR(50),
	@ParentGuardianLastName VARCHAR(50),
	@ParentGuardianMiddleName VARCHAR(50),
	@PrimaryLibrary INT,
	@LibraryCard VARCHAR(20),
	@SchoolName VARCHAR(50),
	@District VARCHAR(50),
	@Teacher VARCHAR(20),
	@GroupTeamName VARCHAR(20),
	@SchoolType INT,
	@LiteracyLevel1 INT,
	@LiteracyLevel2 INT,
	@ParentPermFlag BIT,
	@Over18Flag BIT,
	@ShareFlag BIT,
	@TermsOfUseflag BIT,
	@Custom1 VARCHAR(50),
	@Custom2 VARCHAR(50),
	@Custom3 VARCHAR(50),
	@Custom4 VARCHAR(50),
	@Custom5 VARCHAR(50),
	@AvatarID INT,
	@SDistrict INT,
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = '',
	@Score1 INT = 0,
	@Score2 INT = 0,
	@Score1Pct DECIMAL(18, 2) = 0,
	@Score2Pct DECIMAL(18, 2) = 0,
	@Score1Date DATETIME,
	@Score2Date DATETIME
	)
AS
UPDATE Patron
SET IsMasterAccount = @IsMasterAccount,
	MasterAcctPID = @MasterAcctPID,
	Username = @Username,
	Password = @Password,
	DOB = @DOB,
	Age = @Age,
	SchoolGrade = @SchoolGrade,
	ProgID = @ProgID,
	FirstName = @FirstName,
	MiddleName = @MiddleName,
	LastName = @LastName,
	Gender = @Gender,
	EmailAddress = @EmailAddress,
	PhoneNumber = @PhoneNumber,
	StreetAddress1 = @StreetAddress1,
	StreetAddress2 = @StreetAddress2,
	City = @City,
	STATE = @State,
	ZipCode = @ZipCode,
	Country = @Country,
	County = @County,
	ParentGuardianFirstName = @ParentGuardianFirstName,
	ParentGuardianLastName = @ParentGuardianLastName,
	ParentGuardianMiddleName = @ParentGuardianMiddleName,
	PrimaryLibrary = @PrimaryLibrary,
	LibraryCard = @LibraryCard,
	SchoolName = @SchoolName,
	District = @District,
	Teacher = @Teacher,
	GroupTeamName = @GroupTeamName,
	SchoolType = @SchoolType,
	LiteracyLevel1 = @LiteracyLevel1,
	LiteracyLevel2 = @LiteracyLevel2,
	ParentPermFlag = @ParentPermFlag,
	Over18Flag = @Over18Flag,
	ShareFlag = @ShareFlag,
	TermsOfUseflag = @TermsOfUseflag,
	Custom1 = @Custom1,
	Custom2 = @Custom2,
	Custom3 = @Custom3,
	Custom4 = @Custom4,
	Custom5 = @Custom5,
	AvatarID = @AvatarID,
	SDistrict = @SDistrict,
	TenID = @TenID,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3,
	Score1 = @Score1,
	Score2 = @Score2,
	Score1Pct = @Score1Pct,
	Score2Pct = @Score2Pct,
	Score1Date = @Score1Date,
	Score2Date = @Score2Date
WHERE PID = @PID
	AND TenID = @TenID
