
--Create the Insert Proc
CREATE PROCEDURE [dbo].[app_PrizeTemplate_Insert] (
	@TName VARCHAR(150),
	@NumPrizes INT,
	@IncPrevWinnersFlag BIT,
	@SendNotificationFlag BIT,
	@NotificationSubject VARCHAR(250),
	@NotificationMessage TEXT,
	@ProgID INT,
	@Gender VARCHAR(1),
	@SchoolName VARCHAR(50),
	@PrimaryLibrary INT,
	@MinPoints INT,
	@MaxPoints INT,
	@LogDateStart DATETIME,
	@LogDateEnd DATETIME,
	@MinReviews INT,
	@MaxReviews INT,
	@ReviewDateStart DATETIME,
	@ReviewDateEnd DATETIME,
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = '',
	@TID INT OUTPUT
	)
AS
BEGIN
	INSERT INTO PrizeTemplate (
		TName,
		NumPrizes,
		IncPrevWinnersFlag,
		SendNotificationFlag,
		NotificationSubject,
		NotificationMessage,
		ProgID,
		Gender,
		SchoolName,
		PrimaryLibrary,
		MinPoints,
		MaxPoints,
		LogDateStart,
		LogDateEnd,
		MinReviews,
		MaxReviews,
		ReviewDateStart,
		ReviewDateEnd,
		LastModDate,
		LastModUser,
		AddedDate,
		AddedUser,
		TenID,
		FldInt1,
		FldInt2,
		FldInt3,
		FldBit1,
		FldBit2,
		FldBit3,
		FldText1,
		FldText2,
		FldText3
		)
	VALUES (
		@TName,
		@NumPrizes,
		@IncPrevWinnersFlag,
		@SendNotificationFlag,
		@NotificationSubject,
		@NotificationMessage,
		@ProgID,
		@Gender,
		@SchoolName,
		@PrimaryLibrary,
		@MinPoints,
		@MaxPoints,
		@LogDateStart,
		@LogDateEnd,
		@MinReviews,
		@MaxReviews,
		@ReviewDateStart,
		@ReviewDateEnd,
		@LastModDate,
		@LastModUser,
		@AddedDate,
		@AddedUser,
		@TenID,
		@FldInt1,
		@FldInt2,
		@FldInt3,
		@FldBit1,
		@FldBit2,
		@FldBit3,
		@FldText1,
		@FldText2,
		@FldText3
		)

	SELECT @TID = SCOPE_IDENTITY()
END
