
CREATE PROCEDURE [dbo].[app_Badge_Insert] (
	@AdminName VARCHAR(50),
	@UserName VARCHAR(50),
	@GenNotificationFlag BIT,
	@NotificationSubject VARCHAR(150),
	@NotificationBody TEXT,
	@CustomEarnedMessage TEXT,
	@IncludesPhysicalPrizeFlag BIT,
	@PhysicalPrizeName VARCHAR(50),
	@AssignProgramPrizeCode BIT,
	@PCNotificationSubject VARCHAR(150),
	@PCNotificationBody TEXT,
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = '',
	@BID INT OUTPUT
	)
AS
BEGIN
	INSERT INTO Badge (
		AdminName,
		UserName,
		GenNotificationFlag,
		NotificationSubject,
		NotificationBody,
		CustomEarnedMessage,
		IncludesPhysicalPrizeFlag,
		PhysicalPrizeName,
		AssignProgramPrizeCode,
		PCNotificationSubject,
		PCNotificationBody,
		LastModDate,
		LastModUser,
		AddedDate,
		AddedUser,
		TenID,
		FldInt1,
		FldInt2,
		FldInt3,
		FldBit1,
		FldBit2,
		FldBit3,
		FldText1,
		FldText2,
		FldText3
		)
	VALUES (
		@AdminName,
		@UserName,
		@GenNotificationFlag,
		@NotificationSubject,
		@NotificationBody,
		@CustomEarnedMessage,
		@IncludesPhysicalPrizeFlag,
		@PhysicalPrizeName,
		@AssignProgramPrizeCode,
		@PCNotificationSubject,
		@PCNotificationBody,
		@LastModDate,
		@LastModUser,
		@AddedDate,
		@AddedUser,
		@TenID,
		@FldInt1,
		@FldInt2,
		@FldInt3,
		@FldBit1,
		@FldBit2,
		@FldBit3,
		@FldText1,
		@FldText2,
		@FldText3
		)

	SELECT @BID = SCOPE_IDENTITY()
END
