
--Create the Update Proc
CREATE PROCEDURE [dbo].[app_SurveyResults_Update] (
	@SRID INT,
	@TenID INT,
	@PID INT,
	@SID INT,
	@StartDate DATETIME,
	@EndDate DATETIME,
	@IsComplete BIT,
	@IsScorable BIT,
	@LastAnswered INT,
	@Score INT,
	@ScorePct DECIMAL,
	@Source VARCHAR(50),
	@SourceID INT,
	@FldInt1 INT,
	@FldInt2 INT,
	@FldInt3 INT,
	@FldBit1 BIT,
	@FldBit2 BIT,
	@FldBit3 BIT,
	@FldText1 TEXT,
	@FldText2 TEXT,
	@FldText3 TEXT
	)
AS
UPDATE SurveyResults
SET TenID = @TenID,
	PID = @PID,
	SID = @SID,
	StartDate = @StartDate,
	EndDate = @EndDate,
	IsComplete = @IsComplete,
	IsScorable = @IsScorable,
	LastAnswered = @LastAnswered,
	Score = @Score,
	ScorePct = @ScorePct,
	Source = @Source,
	SourceID = @SourceID,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3
WHERE SRID = @SRID
