
--Create the Update Proc
CREATE PROCEDURE [dbo].[app_Tenant_Update] (
	@TenID INT,
	@Name VARCHAR(150),
	@LandingName VARCHAR(50),
	@AdminName VARCHAR(50),
	@isActiveFlag BIT,
	@isMasterFlag BIT,
	@Description TEXT,
	@DomainName VARCHAR(50),
	@showNotifications BIT,
	@showOffers BIT,
	@showBadges BIT,
	@showEvents BIT,
	@NotificationsMenuText VARCHAR(50),
	@OffersMenuText VARCHAR(50),
	@BadgesMenuText VARCHAR(50),
	@EventsMenuText VARCHAR(50),
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@FldInt1 INT,
	@FldInt2 INT,
	@FldInt3 INT,
	@FldBit1 BIT,
	@FldBit2 BIT,
	@FldBit3 BIT,
	@FldText1 TEXT,
	@FldText2 TEXT,
	@FldText3 TEXT
	)
AS
UPDATE Tenant
SET NAME = @Name,
	LandingName = @LandingName,
	AdminName = @AdminName,
	isActiveFlag = @isActiveFlag,
	isMasterFlag = @isMasterFlag,
	Description = @Description,
	DomainName = @DomainName,
	showNotifications = @showNotifications,
	showOffers = @showOffers,
	showBadges = @showBadges,
	showEvents = @showEvents,
	NotificationsMenuText = @NotificationsMenuText,
	OffersMenuText = @OffersMenuText,
	BadgesMenuText = @BadgesMenuText,
	EventsMenuText = @EventsMenuText,
	LastModDate = @LastModDate,
	LastModUser = @LastModUser,
	AddedDate = @AddedDate,
	AddedUser = @AddedUser,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3
WHERE TenID = @TenID
