
CREATE PROCEDURE [dbo].[app_RegistrationSettings_Insert] (
	@Literacy1Label VARCHAR(50),
	@Literacy2Label VARCHAR(50),
	@DOB_Prompt BIT,
	@Age_Prompt BIT,
	@SchoolGrade_Prompt BIT,
	@FirstName_Prompt BIT,
	@MiddleName_Prompt BIT,
	@LastName_Prompt BIT,
	@Gender_Prompt BIT,
	@EmailAddress_Prompt BIT,
	@PhoneNumber_Prompt BIT,
	@StreetAddress1_Prompt BIT,
	@StreetAddress2_Prompt BIT,
	@City_Prompt BIT,
	@State_Prompt BIT,
	@ZipCode_Prompt BIT,
	@Country_Prompt BIT,
	@County_Prompt BIT,
	@ParentGuardianFirstName_Prompt BIT,
	@ParentGuardianLastName_Prompt BIT,
	@ParentGuardianMiddleName_Prompt BIT,
	@PrimaryLibrary_Prompt BIT,
	@LibraryCard_Prompt BIT,
	@SchoolName_Prompt BIT,
	@District_Prompt BIT,
	@Teacher_Prompt BIT,
	@GroupTeamName_Prompt BIT,
	@SchoolType_Prompt BIT,
	@LiteracyLevel1_Prompt BIT,
	@LiteracyLevel2_Prompt BIT,
	@ParentPermFlag_Prompt BIT,
	@Over18Flag_Prompt BIT,
	@ShareFlag_Prompt BIT,
	@TermsOfUseflag_Prompt BIT,
	@Custom1_Prompt BIT,
	@Custom2_Prompt BIT,
	@Custom3_Prompt BIT,
	@Custom4_Prompt BIT,
	@Custom5_Prompt BIT,
	@DOB_Req BIT,
	@Age_Req BIT,
	@SchoolGrade_Req BIT,
	@FirstName_Req BIT,
	@MiddleName_Req BIT,
	@LastName_Req BIT,
	@Gender_Req BIT,
	@EmailAddress_Req BIT,
	@PhoneNumber_Req BIT,
	@StreetAddress1_Req BIT,
	@StreetAddress2_Req BIT,
	@City_Req BIT,
	@State_Req BIT,
	@ZipCode_Req BIT,
	@Country_Req BIT,
	@County_Req BIT,
	@ParentGuardianFirstName_Req BIT,
	@ParentGuardianLastName_Req BIT,
	@ParentGuardianMiddleName_Req BIT,
	@PrimaryLibrary_Req BIT,
	@LibraryCard_Req BIT,
	@SchoolName_Req BIT,
	@District_Req BIT,
	@Teacher_Req BIT,
	@GroupTeamName_Req BIT,
	@SchoolType_Req BIT,
	@LiteracyLevel1_Req BIT,
	@LiteracyLevel2_Req BIT,
	@ParentPermFlag_Req BIT,
	@Over18Flag_Req BIT,
	@ShareFlag_Req BIT,
	@TermsOfUseflag_Req BIT,
	@Custom1_Req BIT,
	@Custom2_Req BIT,
	@Custom3_Req BIT,
	@Custom4_Req BIT,
	@Custom5_Req BIT,
	@DOB_Show BIT,
	@Age_Show BIT,
	@SchoolGrade_Show BIT,
	@FirstName_Show BIT,
	@MiddleName_Show BIT,
	@LastName_Show BIT,
	@Gender_Show BIT,
	@EmailAddress_Show BIT,
	@PhoneNumber_Show BIT,
	@StreetAddress1_Show BIT,
	@StreetAddress2_Show BIT,
	@City_Show BIT,
	@State_Show BIT,
	@ZipCode_Show BIT,
	@Country_Show BIT,
	@County_Show BIT,
	@ParentGuardianFirstName_Show BIT,
	@ParentGuardianLastName_Show BIT,
	@ParentGuardianMiddleName_Show BIT,
	@PrimaryLibrary_Show BIT,
	@LibraryCard_Show BIT,
	@SchoolName_Show BIT,
	@District_Show BIT,
	@Teacher_Show BIT,
	@GroupTeamName_Show BIT,
	@SchoolType_Show BIT,
	@LiteracyLevel1_Show BIT,
	@LiteracyLevel2_Show BIT,
	@ParentPermFlag_Show BIT,
	@Over18Flag_Show BIT,
	@ShareFlag_Show BIT,
	@TermsOfUseflag_Show BIT,
	@Custom1_Show BIT,
	@Custom2_Show BIT,
	@Custom3_Show BIT,
	@Custom4_Show BIT,
	@Custom5_Show BIT,
	@DOB_Edit BIT,
	@Age_Edit BIT,
	@SchoolGrade_Edit BIT,
	@FirstName_Edit BIT,
	@MiddleName_Edit BIT,
	@LastName_Edit BIT,
	@Gender_Edit BIT,
	@EmailAddress_Edit BIT,
	@PhoneNumber_Edit BIT,
	@StreetAddress1_Edit BIT,
	@StreetAddress2_Edit BIT,
	@City_Edit BIT,
	@State_Edit BIT,
	@ZipCode_Edit BIT,
	@Country_Edit BIT,
	@County_Edit BIT,
	@ParentGuardianFirstName_Edit BIT,
	@ParentGuardianLastName_Edit BIT,
	@ParentGuardianMiddleName_Edit BIT,
	@PrimaryLibrary_Edit BIT,
	@LibraryCard_Edit BIT,
	@SchoolName_Edit BIT,
	@District_Edit BIT,
	@Teacher_Edit BIT,
	@GroupTeamName_Edit BIT,
	@SchoolType_Edit BIT,
	@LiteracyLevel1_Edit BIT,
	@LiteracyLevel2_Edit BIT,
	@ParentPermFlag_Edit BIT,
	@Over18Flag_Edit BIT,
	@ShareFlag_Edit BIT,
	@TermsOfUseflag_Edit BIT,
	@Custom1_Edit BIT,
	@Custom2_Edit BIT,
	@Custom3_Edit BIT,
	@Custom4_Edit BIT,
	@Custom5_Edit BIT,
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@SDistrict_Prompt BIT,
	@SDistrict_Req BIT,
	@SDistrict_Show BIT,
	@SDistrict_Edit BIT,
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = '',
	@RID INT OUTPUT
	)
AS
BEGIN
	INSERT INTO RegistrationSettings (
		Literacy1Label,
		Literacy2Label,
		DOB_Prompt,
		Age_Prompt,
		SchoolGrade_Prompt,
		FirstName_Prompt,
		MiddleName_Prompt,
		LastName_Prompt,
		Gender_Prompt,
		EmailAddress_Prompt,
		PhoneNumber_Prompt,
		StreetAddress1_Prompt,
		StreetAddress2_Prompt,
		City_Prompt,
		State_Prompt,
		ZipCode_Prompt,
		Country_Prompt,
		County_Prompt,
		ParentGuardianFirstName_Prompt,
		ParentGuardianLastName_Prompt,
		ParentGuardianMiddleName_Prompt,
		PrimaryLibrary_Prompt,
		LibraryCard_Prompt,
		SchoolName_Prompt,
		District_Prompt,
		Teacher_Prompt,
		GroupTeamName_Prompt,
		SchoolType_Prompt,
		LiteracyLevel1_Prompt,
		LiteracyLevel2_Prompt,
		ParentPermFlag_Prompt,
		Over18Flag_Prompt,
		ShareFlag_Prompt,
		TermsOfUseflag_Prompt,
		Custom1_Prompt,
		Custom2_Prompt,
		Custom3_Prompt,
		Custom4_Prompt,
		Custom5_Prompt,
		DOB_Req,
		Age_Req,
		SchoolGrade_Req,
		FirstName_Req,
		MiddleName_Req,
		LastName_Req,
		Gender_Req,
		EmailAddress_Req,
		PhoneNumber_Req,
		StreetAddress1_Req,
		StreetAddress2_Req,
		City_Req,
		State_Req,
		ZipCode_Req,
		Country_Req,
		County_Req,
		ParentGuardianFirstName_Req,
		ParentGuardianLastName_Req,
		ParentGuardianMiddleName_Req,
		PrimaryLibrary_Req,
		LibraryCard_Req,
		SchoolName_Req,
		District_Req,
		Teacher_Req,
		GroupTeamName_Req,
		SchoolType_Req,
		LiteracyLevel1_Req,
		LiteracyLevel2_Req,
		ParentPermFlag_Req,
		Over18Flag_Req,
		ShareFlag_Req,
		TermsOfUseflag_Req,
		Custom1_Req,
		Custom2_Req,
		Custom3_Req,
		Custom4_Req,
		Custom5_Req,
		DOB_Show,
		Age_Show,
		SchoolGrade_Show,
		FirstName_Show,
		MiddleName_Show,
		LastName_Show,
		Gender_Show,
		EmailAddress_Show,
		PhoneNumber_Show,
		StreetAddress1_Show,
		StreetAddress2_Show,
		City_Show,
		State_Show,
		ZipCode_Show,
		Country_Show,
		County_Show,
		ParentGuardianFirstName_Show,
		ParentGuardianLastName_Show,
		ParentGuardianMiddleName_Show,
		PrimaryLibrary_Show,
		LibraryCard_Show,
		SchoolName_Show,
		District_Show,
		Teacher_Show,
		GroupTeamName_Show,
		SchoolType_Show,
		LiteracyLevel1_Show,
		LiteracyLevel2_Show,
		ParentPermFlag_Show,
		Over18Flag_Show,
		ShareFlag_Show,
		TermsOfUseflag_Show,
		Custom1_Show,
		Custom2_Show,
		Custom3_Show,
		Custom4_Show,
		Custom5_Show,
		DOB_Edit,
		Age_Edit,
		SchoolGrade_Edit,
		FirstName_Edit,
		MiddleName_Edit,
		LastName_Edit,
		Gender_Edit,
		EmailAddress_Edit,
		PhoneNumber_Edit,
		StreetAddress1_Edit,
		StreetAddress2_Edit,
		City_Edit,
		State_Edit,
		ZipCode_Edit,
		Country_Edit,
		County_Edit,
		ParentGuardianFirstName_Edit,
		ParentGuardianLastName_Edit,
		ParentGuardianMiddleName_Edit,
		PrimaryLibrary_Edit,
		LibraryCard_Edit,
		SchoolName_Edit,
		District_Edit,
		Teacher_Edit,
		GroupTeamName_Edit,
		SchoolType_Edit,
		LiteracyLevel1_Edit,
		LiteracyLevel2_Edit,
		ParentPermFlag_Edit,
		Over18Flag_Edit,
		ShareFlag_Edit,
		TermsOfUseflag_Edit,
		Custom1_Edit,
		Custom2_Edit,
		Custom3_Edit,
		Custom4_Edit,
		Custom5_Edit,
		LastModDate,
		LastModUser,
		AddedDate,
		AddedUser,
		SDistrict_Prompt,
		SDistrict_Req,
		SDistrict_Show,
		SDistrict_Edit,
		TenID,
		FldInt1,
		FldInt2,
		FldInt3,
		FldBit1,
		FldBit2,
		FldBit3,
		FldText1,
		FldText2,
		FldText3
		)
	VALUES (
		@Literacy1Label,
		@Literacy2Label,
		@DOB_Prompt,
		@Age_Prompt,
		@SchoolGrade_Prompt,
		@FirstName_Prompt,
		@MiddleName_Prompt,
		@LastName_Prompt,
		@Gender_Prompt,
		@EmailAddress_Prompt,
		@PhoneNumber_Prompt,
		@StreetAddress1_Prompt,
		@StreetAddress2_Prompt,
		@City_Prompt,
		@State_Prompt,
		@ZipCode_Prompt,
		@Country_Prompt,
		@County_Prompt,
		@ParentGuardianFirstName_Prompt,
		@ParentGuardianLastName_Prompt,
		@ParentGuardianMiddleName_Prompt,
		@PrimaryLibrary_Prompt,
		@LibraryCard_Prompt,
		@SchoolName_Prompt,
		@District_Prompt,
		@Teacher_Prompt,
		@GroupTeamName_Prompt,
		@SchoolType_Prompt,
		@LiteracyLevel1_Prompt,
		@LiteracyLevel2_Prompt,
		@ParentPermFlag_Prompt,
		@Over18Flag_Prompt,
		@ShareFlag_Prompt,
		@TermsOfUseflag_Prompt,
		@Custom1_Prompt,
		@Custom2_Prompt,
		@Custom3_Prompt,
		@Custom4_Prompt,
		@Custom5_Prompt,
		@DOB_Req,
		@Age_Req,
		@SchoolGrade_Req,
		@FirstName_Req,
		@MiddleName_Req,
		@LastName_Req,
		@Gender_Req,
		@EmailAddress_Req,
		@PhoneNumber_Req,
		@StreetAddress1_Req,
		@StreetAddress2_Req,
		@City_Req,
		@State_Req,
		@ZipCode_Req,
		@Country_Req,
		@County_Req,
		@ParentGuardianFirstName_Req,
		@ParentGuardianLastName_Req,
		@ParentGuardianMiddleName_Req,
		@PrimaryLibrary_Req,
		@LibraryCard_Req,
		@SchoolName_Req,
		@District_Req,
		@Teacher_Req,
		@GroupTeamName_Req,
		@SchoolType_Req,
		@LiteracyLevel1_Req,
		@LiteracyLevel2_Req,
		@ParentPermFlag_Req,
		@Over18Flag_Req,
		@ShareFlag_Req,
		@TermsOfUseflag_Req,
		@Custom1_Req,
		@Custom2_Req,
		@Custom3_Req,
		@Custom4_Req,
		@Custom5_Req,
		@DOB_Show,
		@Age_Show,
		@SchoolGrade_Show,
		@FirstName_Show,
		@MiddleName_Show,
		@LastName_Show,
		@Gender_Show,
		@EmailAddress_Show,
		@PhoneNumber_Show,
		@StreetAddress1_Show,
		@StreetAddress2_Show,
		@City_Show,
		@State_Show,
		@ZipCode_Show,
		@Country_Show,
		@County_Show,
		@ParentGuardianFirstName_Show,
		@ParentGuardianLastName_Show,
		@ParentGuardianMiddleName_Show,
		@PrimaryLibrary_Show,
		@LibraryCard_Show,
		@SchoolName_Show,
		@District_Show,
		@Teacher_Show,
		@GroupTeamName_Show,
		@SchoolType_Show,
		@LiteracyLevel1_Show,
		@LiteracyLevel2_Show,
		@ParentPermFlag_Show,
		@Over18Flag_Show,
		@ShareFlag_Show,
		@TermsOfUseflag_Show,
		@Custom1_Show,
		@Custom2_Show,
		@Custom3_Show,
		@Custom4_Show,
		@Custom5_Show,
		@DOB_Edit,
		@Age_Edit,
		@SchoolGrade_Edit,
		@FirstName_Edit,
		@MiddleName_Edit,
		@LastName_Edit,
		@Gender_Edit,
		@EmailAddress_Edit,
		@PhoneNumber_Edit,
		@StreetAddress1_Edit,
		@StreetAddress2_Edit,
		@City_Edit,
		@State_Edit,
		@ZipCode_Edit,
		@Country_Edit,
		@County_Edit,
		@ParentGuardianFirstName_Edit,
		@ParentGuardianLastName_Edit,
		@ParentGuardianMiddleName_Edit,
		@PrimaryLibrary_Edit,
		@LibraryCard_Edit,
		@SchoolName_Edit,
		@District_Edit,
		@Teacher_Edit,
		@GroupTeamName_Edit,
		@SchoolType_Edit,
		@LiteracyLevel1_Edit,
		@LiteracyLevel2_Edit,
		@ParentPermFlag_Edit,
		@Over18Flag_Edit,
		@ShareFlag_Edit,
		@TermsOfUseflag_Edit,
		@Custom1_Edit,
		@Custom2_Edit,
		@Custom3_Edit,
		@Custom4_Edit,
		@Custom5_Edit,
		@LastModDate,
		@LastModUser,
		@AddedDate,
		@AddedUser,
		@SDistrict_Prompt,
		@SDistrict_Req,
		@SDistrict_Show,
		@SDistrict_Edit,
		@TenID,
		@FldInt1,
		@FldInt2,
		@FldInt3,
		@FldBit1,
		@FldBit2,
		@FldBit3,
		@FldText1,
		@FldText2,
		@FldText3
		)

	SELECT @RID = SCOPE_IDENTITY()
END
