
--Create the Update Proc
CREATE PROCEDURE [dbo].[app_PrizeTemplate_Update] (
	@TID INT,
	@TName VARCHAR(150),
	@NumPrizes INT,
	@IncPrevWinnersFlag BIT,
	@SendNotificationFlag BIT,
	@NotificationSubject VARCHAR(250),
	@NotificationMessage TEXT,
	@ProgID INT,
	@Gender VARCHAR(1),
	@SchoolName VARCHAR(50),
	@PrimaryLibrary INT,
	@MinPoints INT,
	@MaxPoints INT,
	@LogDateStart DATETIME,
	@LogDateEnd DATETIME,
	@MinReviews INT,
	@MaxReviews INT,
	@ReviewDateStart DATETIME,
	@ReviewDateEnd DATETIME,
	@LastModDate DATETIME,
	@LastModUser VARCHAR(50),
	@AddedDate DATETIME,
	@AddedUser VARCHAR(50),
	@TenID INT = 0,
	@FldInt1 INT = 0,
	@FldInt2 INT = 0,
	@FldInt3 INT = 0,
	@FldBit1 BIT = 0,
	@FldBit2 BIT = 0,
	@FldBit3 BIT = 0,
	@FldText1 TEXT = '',
	@FldText2 TEXT = '',
	@FldText3 TEXT = ''
	)
AS
UPDATE PrizeTemplate
SET TName = @TName,
	NumPrizes = @NumPrizes,
	IncPrevWinnersFlag = @IncPrevWinnersFlag,
	SendNotificationFlag = @SendNotificationFlag,
	NotificationSubject = @NotificationSubject,
	NotificationMessage = @NotificationMessage,
	ProgID = @ProgID,
	Gender = @Gender,
	SchoolName = @SchoolName,
	PrimaryLibrary = @PrimaryLibrary,
	MinPoints = @MinPoints,
	MaxPoints = @MaxPoints,
	LogDateStart = @LogDateStart,
	LogDateEnd = @LogDateEnd,
	MinReviews = @MinReviews,
	MaxReviews = @MaxReviews,
	ReviewDateStart = @ReviewDateStart,
	ReviewDateEnd = @ReviewDateEnd,
	LastModDate = @LastModDate,
	LastModUser = @LastModUser,
	AddedDate = @AddedDate,
	AddedUser = @AddedUser,
	TenID = @TenID,
	FldInt1 = @FldInt1,
	FldInt2 = @FldInt2,
	FldInt3 = @FldInt3,
	FldBit1 = @FldBit1,
	FldBit2 = @FldBit2,
	FldBit3 = @FldBit3,
	FldText1 = @FldText1,
	FldText2 = @FldText2,
	FldText3 = @FldText3
WHERE TID = @TID
	AND TenID = @TenID
