
CREATE PROCEDURE [dbo].[app_Patron_Login] @UserName VARCHAR(50),
	@Password VARCHAR(255),
	@SessionID VARCHAR(128)
AS
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @Count INT,
	@UID INT

SELECT @Count = isnull(Count(*), 0),
	@UID = PID
FROM dbo.Patron
WHERE Username = @UserName
	AND Password = @Password
GROUP BY PID

IF @Count = 0
	OR @Count IS NULL
BEGIN
	SELECT 0
END
ELSE
BEGIN
	SELECT 1
END

RETURN 0
