
CREATE PROCEDURE [dbo].[app_Badge_GetBadgeBranches] @BID INT,
	@TenID INT
AS
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @CTID INT

SELECT @CTID = CTID
FROM dbo.CodeType
WHERE TenID = @TenID
	AND CodeTypeName = 'Branch'

SELECT @BID AS BID,
	c.CID,
	c.Code AS NAME, --c.CTID,
	CASE 
		WHEN bb.BID IS NULL
			THEN 0
		ELSE 1
		END AS Checked
FROM dbo.BadgeBranch bb
RIGHT OUTER JOIN Code c ON bb.CID = c.CID
	AND (bb.BID = @BID OR bb.BID IS NULL)
WHERE c.TenID = @TenID
	AND c.CTID = @CTID
ORDER BY c.Code
