namespace GRA.Domain.Model
{
    public enum Permission
    {
        AccessMissionControl,
        AddCategories,
        AddChallenges,
        AddPages,
        DeleteAnyMail,
        DeleteCategories,
        DeletePages,
        DeleteParticipants,
        EditCategories,
        EditChallenges,
        EditPages,
        EditParticipants,
        LogActivityForAny,
        MailParticipants,
        PerformDrawing,
        ReadAllMail,
        RemoveChallenges,
        SendBroadcastMail,
        ViewParticipantList,
        ViewParticipantDetails,
        ViewAllReporting,
        ViewUnpublishedPages,
        ViewUserDrawings
    }
}