name: ci
run-name: ${{ github.actor }} is running ci

on: [push, pull_request]

jobs:
  build-docker-image:
    name: "GRA Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: gra
          CR_HOST: ${{secrets.CR_HOST}}
          CR_OWNER: ${{secrets.CR_OWNER}}
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_OWNER: ${{secrets.GHCR_OWNER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash -p

      - uses: actions/upload-artifact@v4
        with:
          name: Great Reading Adventure
          path: package/GreatReadingAdventure-*.zip
          if-no-files-found: ignore
