CREATE TABLE [dbo].[BookList] (
    [BLID]               INT          IDENTITY (1, 1) NOT NULL,
    [AdminName]          NVARCHAR(255) NULL,
    [ListName]           NVARCHAR(255) NULL,
    [AdminDescription]   TEXT         NULL,
    [Description]        TEXT         NULL,
    [LiteracyLevel1]     INT          NULL,
    [LiteracyLevel2]     INT          NULL,
    [ProgID]             INT          NULL,
    [LibraryID]          INT          NULL,
    [AwardBadgeID]       INT          NULL,
    [AwardPoints]        INT          NULL,
    [LastModDate]        DATETIME     CONSTRAINT [DF_BookList_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser]        VARCHAR (50) CONSTRAINT [DF_BookList_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]          DATETIME     CONSTRAINT [DF_BookList_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]          VARCHAR (50) CONSTRAINT [DF_BookList_AddedUser] DEFAULT ('N/A') NULL,
    [TenID]              INT          NULL,
    [FldInt1]            INT          NULL,
    [FldInt2]            INT          NULL,
    [FldInt3]            INT          NULL,
    [FldBit1]            BIT          NULL,
    [FldBit2]            BIT          NULL,
    [FldBit3]            BIT          NULL,
    [FldText1]           TEXT         NULL,
    [FldText2]           TEXT         NULL,
    [FldText3]           TEXT         NULL,
    [NumBooksToComplete] INT          NULL,
    CONSTRAINT [PK_BookList] PRIMARY KEY CLUSTERED ([BLID] ASC)
);

