CREATE TABLE [dbo].[CustomRegistrationFields] (
    [CID]         INT          IDENTITY (1, 1) NOT NULL,
    [Use1]        BIT          CONSTRAINT [DF_CustomRegistrationFields_Use1] DEFAULT ((0)) NULL,
    [Label1]      VARCHAR (50) NULL,
    [DDValues1]   VARCHAR (50) NULL,
    [Use2]        BIT          CONSTRAINT [DF_CustomRegistrationFields_Use2] DEFAULT ((0)) NULL,
    [Use3]        BIT          CONSTRAINT [DF_CustomRegistrationFields_Use3] DEFAULT ((0)) NULL,
    [Use4]        BIT          CONSTRAINT [DF_CustomRegistrationFields_Use4] DEFAULT ((0)) NULL,
    [Use5]        BIT          CONSTRAINT [DF_CustomRegistrationFields_Use5] DEFAULT ((0)) NULL,
    [Label2]      VARCHAR (50) NULL,
    [Label3]      VARCHAR (50) NULL,
    [Label4]      VARCHAR (50) NULL,
    [Label5]      VARCHAR (50) NULL,
    [DDValues2]   VARCHAR (50) NULL,
    [DDValues3]   VARCHAR (50) NULL,
    [DDValues4]   VARCHAR (50) NULL,
    [DDValues5]   VARCHAR (50) NULL,
    [LastModDate] DATETIME     CONSTRAINT [DF_CustomRegistrationFields_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser] VARCHAR (50) CONSTRAINT [DF_CustomRegistrationFields_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]   DATETIME     CONSTRAINT [DF_CustomRegistrationFields_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]   VARCHAR (50) CONSTRAINT [DF_CustomRegistrationFields_AddedUser] DEFAULT ('N/A') NULL,
    [TenID]       INT          NULL,
    [FldInt1]     INT          NULL,
    [FldInt2]     INT          NULL,
    [FldInt3]     INT          NULL,
    [FldBit1]     BIT          NULL,
    [FldBit2]     BIT          NULL,
    [FldBit3]     BIT          NULL,
    [FldText1]    TEXT         NULL,
    [FldText2]    TEXT         NULL,
    [FldText3]    TEXT         NULL,
    CONSTRAINT [PK_CustomRegistrationFields] PRIMARY KEY CLUSTERED ([CID] ASC)
);

