CREATE TABLE [dbo].[Event] (
    [EID]              INT           IDENTITY (1, 1) NOT NULL,
    [EventTitle]       NVARCHAR(255) NULL,
    [EventDate]        DATETIME      NULL,
    [EventTime]        VARCHAR (15)  NULL,
    [HTML]             TEXT          NULL,
    [SecretCode]       VARCHAR (50)  NULL,
    [NumberPoints]     INT           NULL,
    [BadgeID]          INT           NULL,
    [BranchID]         INT           NULL,
    [Custom1]          VARCHAR (50)  NULL,
    [Custom2]          VARCHAR (50)  NULL,
    [Custom3]          VARCHAR (50)  NULL,
    [LastModDate]      DATETIME      CONSTRAINT [DF_Event_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser]      VARCHAR (50)  CONSTRAINT [DF_Event_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]        DATETIME      CONSTRAINT [DF_Event_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]        VARCHAR (50)  CONSTRAINT [DF_Event_AddedUser] DEFAULT ('N/A') NULL,
    [TenID]            INT           NULL,
    [FldInt1]          INT           NULL,
    [FldInt2]          INT           NULL,
    [FldInt3]          INT           NULL,
    [FldBit1]          BIT           NULL,
    [FldBit2]          BIT           NULL,
    [FldBit3]          BIT           NULL,
    [FldText1]         TEXT          NULL,
    [FldText2]         TEXT          NULL,
    [FldText3]         TEXT          NULL,
    [EndDate]          DATETIME      NULL,
    [EndTime]          VARCHAR (50)  NULL,
    [ShortDescription] TEXT          NULL,
	[ExternalLinkToEvent]      NVARCHAR(255) NULL,
    [HiddenFromPublic] BIT NULL, 
    CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED ([EID] ASC)
);

