CREATE TABLE [dbo].[Patron] (
    [PID]                      INT             IDENTITY (100000, 1) NOT NULL,
    [IsMasterAccount]          BIT             CONSTRAINT [DF_Patron_IsMasterAccount] DEFAULT ((0)) NULL,
    [MasterAcctPID]            INT             NULL,
    [Username]                 VARCHAR (50)    NULL,
    [Password]                 NVARCHAR(255)    NULL,
    [DOB]                      DATETIME        NULL,
    [Age]                      INT             NULL,
    [SchoolGrade]              VARCHAR (5)     NULL,
    [ProgID]                   INT             NULL,
    [FirstName]                VARCHAR (50)    NULL,
    [MiddleName]               VARCHAR (50)    NULL,
    [LastName]                 VARCHAR (50)    NULL,
    [Gender]                   VARCHAR (1)     NULL,
    [EmailAddress]             VARCHAR (150)   NULL,
    [PhoneNumber]              VARCHAR (20)    NULL,
    [StreetAddress1]           VARCHAR (80)    NULL,
    [StreetAddress2]           VARCHAR (80)    NULL,
    [City]                     VARCHAR (20)    NULL,
    [State]                    VARCHAR (2)     NULL,
    [ZipCode]                  VARCHAR (10)    NULL,
    [Country]                  VARCHAR (50)    NULL,
    [County]                   VARCHAR (50)    NULL,
    [ParentGuardianFirstName]  VARCHAR (50)    NULL,
    [ParentGuardianLastName]   VARCHAR (50)    NULL,
    [ParentGuardianMiddleName] VARCHAR (50)    NULL,
    [PrimaryLibrary]           INT             NULL,
    [LibraryCard]              VARCHAR (20)    NULL,
    [SchoolName]               VARCHAR (50)    NULL,
    [District]                 VARCHAR (50)    NULL,
    [Teacher]                  VARCHAR (20)    NULL,
    [GroupTeamName]            VARCHAR (20)    NULL,
    [SchoolType]               INT             NULL,
    [LiteracyLevel1]           INT             NULL,
    [LiteracyLevel2]           INT             NULL,
    [ParentPermFlag]           BIT             NULL,
    [Over18Flag]               BIT             NULL,
    [ShareFlag]                BIT             NULL,
    [TermsOfUseflag]           BIT             NULL,
    [Custom1]                  VARCHAR (50)    NULL,
    [Custom2]                  VARCHAR (50)    NULL,
    [Custom3]                  VARCHAR (50)    NULL,
    [Custom4]                  VARCHAR (50)    NULL,
    [Custom5]                  VARCHAR (50)    NULL,
    [AvatarID]                 INT             NULL,
    [RegistrationDate]         DATETIME        CONSTRAINT [DF_Patron_RegistrationDate] DEFAULT (getdate()) NULL,
    [SDistrict]                INT             NULL,
    [TenID]                    INT             NULL,
    [FldInt1]                  INT             NULL,
    [FldInt2]                  INT             NULL,
    [FldInt3]                  INT             NULL,
    [FldBit1]                  BIT             NULL,
    [FldBit2]                  BIT             NULL,
    [FldBit3]                  BIT             NULL,
    [FldText1]                 TEXT            NULL,
    [FldText2]                 TEXT            NULL,
    [FldText3]                 TEXT            NULL,
    [Score1]                   INT             CONSTRAINT [DF_Patron_Score1] DEFAULT ((0)) NULL,
    [Score2]                   INT             CONSTRAINT [DF_Patron_Score2] DEFAULT ((0)) NULL,
    [Score1Pct]                DECIMAL (18, 2) CONSTRAINT [DF_Patron_Score1Pct] DEFAULT ((0)) NULL,
    [Score2Pct]                DECIMAL (18, 2) CONSTRAINT [DF_Patron_Score2Pct] DEFAULT ((0)) NULL,
    [Score1Date]               DATETIME        NULL,
    [Score2Date]               DATETIME        NULL,
    CONSTRAINT [PK_Patron] PRIMARY KEY CLUSTERED ([PID] ASC)
);

