CREATE TABLE [dbo].[PrizeTemplate] (
    [TID]                  INT           IDENTITY (1, 1) NOT NULL,
    [TName]                VARCHAR (150) NULL,
    [NumPrizes]            INT           CONSTRAINT [DF_PrizeTemplate_NumPrizes] DEFAULT ((1)) NULL,
    [IncPrevWinnersFlag]   BIT           NULL,
    [SendNotificationFlag] BIT           NULL,
    [NotificationSubject]  VARCHAR (250) NULL,
    [NotificationMessage]  TEXT          NULL,
    [ProgID]               INT           NULL,
    [Gender]               VARCHAR (1)   NULL,
    [SchoolName]           VARCHAR (50)  NULL,
    [PrimaryLibrary]       INT           NULL,
    [MinPoints]            INT           NULL,
    [MaxPoints]            INT           NULL,
    [LogDateStart]         DATETIME      NULL,
    [LogDateEnd]           DATETIME      NULL,
    [MinReviews]           INT           NULL,
    [MaxReviews]           INT           NULL,
    [ReviewDateStart]      DATETIME      NULL,
    [ReviewDateEnd]        DATETIME      NULL,
    [LastModDate]          DATETIME      CONSTRAINT [DF_PrizeTemplate_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser]          VARCHAR (50)  CONSTRAINT [DF_PrizeTemplate_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]            DATETIME      CONSTRAINT [DF_PrizeTemplate_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]            VARCHAR (50)  CONSTRAINT [DF_PrizeTemplate_AddedUser] DEFAULT ('N/A') NULL,
    [TenID]                INT           NULL,
    [FldInt1]              INT           NULL,
    [FldInt2]              INT           NULL,
    [FldInt3]              INT           NULL,
    [FldBit1]              BIT           NULL,
    [FldBit2]              BIT           NULL,
    [FldBit3]              BIT           NULL,
    [FldText1]             TEXT          NULL,
    [FldText2]             TEXT          NULL,
    [FldText3]             TEXT          NULL,
    CONSTRAINT [PK_PrizeTemplate] PRIMARY KEY CLUSTERED ([TID] ASC)
);

