CREATE TABLE [dbo].[ReportTemplate] (
    [RTID]                   INT           IDENTITY (1, 1) NOT NULL,
    [ProgId]                 INT           CONSTRAINT [DF_ReportTemplate_ProgId] DEFAULT ((0)) NULL,
    [ReportName]             NVARCHAR(255) NULL,
    [DisplayFilters]         BIT           NULL,
    [DOBFrom]                DATETIME      NULL,
    [DOBTo]                  DATETIME      NULL,
    [AgeFrom]                INT           NULL,
    [AgeTo]                  INT           NULL,
    [SchoolGrade]            VARCHAR (5)   NULL,
    [FirstName]              VARCHAR (50)  NULL,
    [LastName]               VARCHAR (50)  NULL,
    [Gender]                 VARCHAR (1)   NULL,
    [EmailAddress]           VARCHAR (150) NULL,
    [PhoneNumber]            VARCHAR (20)  NULL,
    [City]                   VARCHAR (20)  NULL,
    [State]                  VARCHAR (2)   NULL,
    [ZipCode]                VARCHAR (10)  NULL,
    [County]                 VARCHAR (50)  NULL,
    [PrimaryLibrary]         INT           NULL,
    [SchoolName]             VARCHAR (50)  NULL,
    [District]               VARCHAR (50)  NULL,
    [Teacher]                VARCHAR (20)  NULL,
    [GroupTeamName]          VARCHAR (20)  NULL,
    [SchoolType]             INT           NULL,
    [LiteracyLevel1]         INT           NULL,
    [LiteracyLevel2]         INT           NULL,
    [Custom1]                VARCHAR (50)  NULL,
    [Custom2]                VARCHAR (50)  NULL,
    [Custom3]                VARCHAR (50)  NULL,
    [Custom4]                VARCHAR (50)  NULL,
    [Custom5]                VARCHAR (50)  NULL,
    [RegistrationDateStart]  DATETIME      CONSTRAINT [DF_ReportTemplate_RegistrationDate1] DEFAULT (getdate()) NULL,
    [RegistrationDateEnd]    DATETIME      CONSTRAINT [DF_ReportTemplate_RegistrationDate] DEFAULT (getdate()) NULL,
    [PointsMin]              INT           NULL,
    [PointsMax]              INT           NULL,
    [PointsStart]            DATETIME      NULL,
    [PointsEnd]              DATETIME      NULL,
    [EventCode]              VARCHAR (50)  NULL,
    [EarnedBadge]            INT           NULL,
    [PhysicalPrizeEarned]    VARCHAR (50)  NULL,
    [PhysicalPrizeRedeemed]  BIT           NULL,
    [PhysicalPrizeStartDate] DATETIME      NULL,
    [PhysicalPrizeEndDate]   DATETIME      NULL,
    [ReviewsMin]             INT           NULL,
    [ReviewsMax]             INT           NULL,
    [ReviewTitle]            VARCHAR (150) NULL,
    [ReviewAuthor]           VARCHAR (100) NULL,
    [ReviewStartDate]        DATETIME      NULL,
    [ReviewEndDate]          DATETIME      NULL,
    [RandomDrawingName]      VARCHAR (50)  NULL,
    [RandomDrawingNum]       INT           NULL,
    [RandomDrawingStartDate] DATETIME      NULL,
    [RandomDrawingEndDate]   DATETIME      NULL,
    [HasBeenDrawn]           BIT           NULL,
    [HasRedeemend]           BIT           NULL,
    [PIDInc]                 BIT           NULL,
    [UsernameInc]            BIT           NULL,
    [DOBInc]                 BIT           NULL,
    [AgeInc]                 BIT           NULL,
    [SchoolGradeInc]         BIT           NULL,
    [FirstNameInc]           BIT           NULL,
    [LastNameInc]            BIT           NULL,
    [GenderInc]              BIT           NULL,
    [EmailAddressInc]        BIT           NULL,
    [PhoneNumberInc]         BIT           NULL,
    [CityInc]                BIT           NULL,
    [StateInc]               BIT           NULL,
    [ZipCodeInc]             BIT           NULL,
    [CountyInc]              BIT           NULL,
    [PrimaryLibraryInc]      BIT           NULL,
    [SchoolNameInc]          BIT           NULL,
    [DistrictInc]            BIT           NULL,
    [TeacherInc]             BIT           NULL,
    [GroupTeamNameInc]       BIT           NULL,
    [SchoolTypeInc]          BIT           NULL,
    [LiteracyLevel1Inc]      BIT           NULL,
    [LiteracyLevel2Inc]      BIT           NULL,
    [Custom1Inc]             BIT           NULL,
    [Custom2Inc]             BIT           NULL,
    [Custom3Inc]             BIT           NULL,
    [Custom4Inc]             BIT           NULL,
    [Custom5Inc]             BIT           NULL,
    [RegistrationDateInc]    BIT           NULL,
    [PointsInc]              BIT           NULL,
    [EarnedBadgeInc]         BIT           NULL,
    [PhysicalPrizeNameInc]   BIT           NOT NULL,
    [PhysicalPrizeDateInc]   BIT           NULL,
    [NumReviewsInc]          BIT           NULL,
    [ReviewAuthorInc]        BIT           NULL,
    [ReviewTitleInc]         BIT           NULL,
    [ReviewDateInc]          BIT           NULL,
    [RandomDrawingNameInc]   BIT           NULL,
    [RandomDrawingNumInc]    BIT           NULL,
    [RandomDrawingDateInc]   BIT           NULL,
    [HasBeenDrawnInc]        BIT           NULL,
    [HasRedeemendInc]        BIT           NULL,
    [LastModDate]            DATETIME      CONSTRAINT [DF_ReportTemplate_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser]            VARCHAR (50)  CONSTRAINT [DF_ReportTemplate_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]              DATETIME      CONSTRAINT [DF_ReportTemplate_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]              VARCHAR (50)  CONSTRAINT [DF_ReportTemplate_AddedUser] DEFAULT ('N/A') NULL,
    [SDistrict]              VARCHAR (50)  NULL,
    [SDistrictInc]           BIT           NULL,
    [TenID]                  INT           NULL,
    [FldInt1]                INT           NULL,
    [FldInt2]                INT           NULL,
    [FldInt3]                INT           NULL,
    [FldBit1]                BIT           NULL,
    [FldBit2]                BIT           NULL,
    [FldBit3]                BIT           NULL,
    [FldText1]               TEXT          NULL,
    [FldText2]               TEXT          NULL,
    [FldText3]               TEXT          NULL,
    [Score1From]             INT           NULL,
    [Score1To]               INT           NULL,
    [Score1PctFrom]          INT           NULL,
    [Score1PctTo]            INT           NULL,
    [Score2From]             INT           NULL,
    [Score2To]               INT           NULL,
    [Score2PctFrom]          INT           NULL,
    [Score2PctTo]            INT           NULL,
    [Score1Inc]              BIT           NULL,
    [Score2Inc]              BIT           NULL,
    [Score1PctInc]           BIT           NULL,
    [Score2PctInc]           BIT           NULL,
    CONSTRAINT [PK_ReportTemplate] PRIMARY KEY CLUSTERED ([RTID] ASC)
);

