CREATE TABLE [dbo].[SRPUser] (
    [UID]               INT           IDENTITY (1000, 1) NOT NULL,
    [Username]          VARCHAR (50)  NOT NULL,
    [Password]          VARCHAR (255)  NOT NULL,
    [FirstName]         NVARCHAR(255)  NULL,
    [LastName]          NVARCHAR(255)  NULL,
    [EmailAddress]      NVARCHAR(255) NOT NULL,
    [Division]          VARCHAR (50)  NULL,
    [Department]        VARCHAR (50)  NULL,
    [Title]             VARCHAR (50)  NULL,
    [IsActive]          BIT           NULL,
    [MustResetPassword] BIT           NULL,
    [IsDeleted]         BIT           NULL,
    [LastPasswordReset] DATETIME      NULL,
    [DeletedDate]       DATETIME      NULL,
    [LastModDate]       DATETIME      CONSTRAINT [DF_SRPUser_LastModDate] DEFAULT (getdate()) NULL,
    [LastModUser]       VARCHAR (50)  CONSTRAINT [DF_SRPUser_LastModUser] DEFAULT ('N/A') NULL,
    [AddedDate]         DATETIME      CONSTRAINT [DF_SRPUser_AddedDate] DEFAULT (getdate()) NULL,
    [AddedUser]         VARCHAR (50)  CONSTRAINT [DF_SRPUser_AddedUser] DEFAULT ('N/A') NULL,
    [TenID]             INT           NULL,
    [FldInt1]           INT           NULL,
    [FldInt2]           INT           NULL,
    [FldInt3]           INT           NULL,
    [FldBit1]           BIT           NULL,
    [FldBit2]           BIT           NULL,
    [FldBit3]           BIT           NULL,
    [FldText1]          TEXT          NULL,
    [FldText2]          TEXT          NULL,
    [FldText3]          TEXT          NULL,
    CONSTRAINT [PK_SRPUser] PRIMARY KEY CLUSTERED ([UID] ASC)
);

