//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG.SRP {
    
    
    public partial class Recover {
        
        /// <summary>
        /// ProgramTabs1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Classes.ProgramTabs ProgramTabs1;
        
        /// <summary>
        /// RecoverPassword1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Classes.RecoverPassword RecoverPassword1;
        
        /// <summary>
        /// ProgramBanner1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Classes.ProgramBanner ProgramBanner1;
    }
}
