//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG.SRP.Controls {
    
    
    public partial class GameboardControl {
        
        /// <summary>
        /// MyPointsControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Controls.MyPointsControl MyPointsControl1;
        
        /// <summary>
        /// LeaderBoardControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Controls.LeaderBoardControl LeaderBoardControl1;
        
        /// <summary>
        /// MyGameLoggingNavControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::STG.SRP.Controls.MyGameLoggingNavControl MyGameLoggingNavControl1;
    }
}
