namespace GRA
{
    public static class Annotations
    {
        public static class Home
        {
            public const string AdventureNotOver = "Your adventure is not over yet!";
            public const string BannerAltTag = "Illustration of a forest.";
            public const string CalendarReminder = "Add a calendar reminder";
            public const string ContinueYourAdventure = "Continue your adventure with a visit to your local library in person or online! Books, movies, audiobooks, graphic novels all await!";
            public const string ForMoreInformation = "For more information about this reading program, visit your local library!";
            public const string GoOnAJourney = "While you're there, go on a journey of discovery! Visit fabulous destinations such as Hogwarts, Narnia, Oz, and Middle Earth!";
            public const string ProgramStartsOn = "You can join our program starting on {0}!";
            public const string Read20 = "Reading for 20 minutes a day helps build a strong lifelong reading habit.";
            public const string ReadingIsFundamental = "Reading is fundamental for developing literacy skills!";
            public const string RemindMe = "Remind Me!";
            public const string SignInAgain = "Sign in again";
            public const string StartAdventure = "Join to get started on your reading adventure!";
            public const string StartsSoon = "Our program starts soon but you can join now to be ready to go when the program starts!";
            public const string StillSignIn = "You can still sign in to review your history and achievements.";
            public const string SubmitEmailBelow = "Submit your email address below and we'll remind you when the program starts.";
            public const string Thanks = "Thanks for participating in {0}!";
            public const string WantAReminder = "Would you like a reminder email for our next reading program? Enter your email address below and click the 'Remind me' button and we'll send you a reminder when you can join.";
            public const string WelcomeTo = "Welcome to {0}.";
            public const string WhenProgramStarts = "When the program starts, you'll be able to join right here. Come back soon!";
        }

        public static class Info
        {
            public const string AnyLibrary = "Any participating library";
            public const string AvailableForPickup = "Available for pickup";
            public const string BadgeInfoError = "Error retrieving badge information.";
            public const string BetterSuitedOption = "This program may be better-suited to your age:";
            public const string ChallengeBadgeEarned = "You earned this badge for completing the challenge: <a href=\"{0}\" target=\"_blank\">{1}</a>";
            public const string ChallengeBookLinkTitle = "Read <strong><em><a href=\"{0}\" target=\"_blank\">{1}</a></em></strong>";
            public const string ChallengeBookLinkTitleAuthor = "Read <strong><em><a href=\"{0}\" target=\"_blank\">{1}</a></em></strong> by <strong>{2}</strong>";
            public const string ChallengeBookTitle = "Read <strong><em>{0}</em></strong>";
            public const string ChallengeBookTitleAuthor = "Read <strong><em>{0}</em></strong> by <strong>{1}</strong>";
            public const string CompletedOnDate = "Completed on: {0}";
            public const string CompleteTasksEarnPoints = "When you complete <strong>{0}</strong>, you will earn <strong>{1}</strong>.";
            public const string CompleteTasksEarnPointsBadge = "When you complete <strong>{0}</strong>, you will earn <strong>{1}</strong> and a badge.";
            public const string ConfirmBookDelete = "Are you sure you want to delete this book from your book list:";
            public const string CouldNotFind = "We couldn't find what you were looking for. Sorry about that!";
            public const string DashboardOptionalFields = "If you choose to enter a title and author, you can view a list of all the books you've read in your profile.";
            public const string EarnedOn = "Earned on {0}";
            public const string EventBadgeEarned = "You earned this badge for attending the event: <a href=\"{0}\" target=\"_blank\">{1}</a>";
            public const string EventLimitedToProgram = "This event is limited to the age group: {0}";
            public const string FreeBookRedeemDashboard = "You've earned a free book! Head over to <a href=\"{0}\"><strong>My Profile</strong></a> page to choose what to do with it.";
            public const string FreeBookRedeemExpirationDashboard = "You've earned a free book! Head over to <a href=\"{0}\"><strong>My Profile</strong></a> page by {1} to choose what to do with it.";
            public const string Goal = "The goal of this program is {0} points.";
            public const string GoalComplete = "You have reached the program's goal!";
            public const string GroupAdd = "Add existing participant to your {0}";
            public const string GroupCannot = "A {0} cannot be created at this time.";
            public const string GroupCreate = "Click below to create a {0}";
            public const string GroupLeader = "You are leader of the group: <a href=\"{0}\"><strong>{1}</strong></a>";
            public const string GroupMember = "You are in the group: <strong>{0}</strong>";
            public const string GroupRegister = "Register new {0} Member";
            public const string LetYouKnowWhen = "Thanks! We'll let you know when you can join the program.";
            public const string MailForHelp = "If you can't find something, please <a href=\"{0}\">send us a mail</a> and let us know what you were looking for, we'll do our best to help.";
            public const string MinutesRead = "Minutes read: <strong>{0:n0}</strong>";
            public const string MinutesReadSoFar = "Minutes read so far: <strong>{0:n0}</strong>";
            public const string NoBadges = "You have not earned any badges yet.";
            public const string NoBooksLogged = "No books logged.";
            public const string NoCertificates = "You have not earned any certificates yet.";
            public const string NoHistory = "No history to display.";
            public const string NoPrizes = "No prizes yet, keep reading!";
            public const string NoUnlockedBundles = "No unlocked bundles";
            public const string OurGoalInMinutes = "Our goal (in minutes): {0:n0}";
            public const string PasswordRecoverySent = "A password recovery email has been sent to the email for username '{0}'.";
            public const string PasswordResetFor = "Password reset for: {0}";
            public const string PickedUp = "Picked up";
            public const string PersonalActivityGoal = "Your personal reading goal is {0} minutes.";
            public const string PersonalGoal = "You have {0}/{1} points towards your personal goal.";
            public const string PersonalGoalComplete = "You have completed your personal goal of {0} points!";
            public const string PointSingular = "{0} point";
            public const string PointsPlural = "{0} points";
            public const string ProgramEnded = "{0} has ended, please join us next time!";
            public const string ReceivedCertificate = "You've received a certificate!";
            public const string RegistrationNotOpenYet = "Registration for {0} is not open yet.";
            public const string SearchResultsMatchesPlural = "There are {0} results matching your search.";
            public const string SearchResultsMatchesSingular = "There is 1 result matching your search.";
            public const string SiteGoalHeader = "Community Reading Goal";
            public const string StatusSaved = "Your status has been saved!";
            public const string StatusSavedPercentage = "Your status has been saved. You have completed {0}% of the required tasks for the challenge: {1}!";
            public const string SuccessfullyJoined = "You've successfully joined <strong>{0}</strong>!";
            public const string TaskSingular = "{0} task";
            public const string TasksPlural = "{0} tasks";
            public const string UpgradeToGroupDescription = "It appears that you have more than {0} members in your family. We'd like you to convert your family to a group in order to add more members.";
            public const string UsernameIsAvailable = "That username is available!";
            public const string UsernameListSent = "A list of usernames associated with the email address '{0}' has been sent.";
            public const string VendorItemArrived = "<em>{0}</em> arrived on <strong>{1}</strong> and is ready for pick-up.";
            public const string VendorItemOrdered = "<em>{0}</em> ordered on <strong>{1}</strong>.";
            public const string VendorItemPickedup = "<em>{0}</em> was picked up on <strong>{1}</strong>.";
            public const string VendorItemShipped = "<em>{0}</em> shipped on <strong>{1}</strong>.";
            public const string WhileSuppliesLast = "Some prizes are available while supplies last, check with your library for more information.";
            public const string YouCanJoinOn = "You can join {0} on {1}.";
        }

        public static class Interface
        {
            public const string ActivityApplied = "Activity applied!";
            public const string AddBook = "Add Book";
            public const string AddBookNotYet = "You will be able to add books once the program starts.";
            public const string AddedParticipantGroupFamily = "Added {0} to your {1}!";
            public const string AddExistingExplanation = "Add an existing participant into your {0}, if that participant is the head of a {0} their {0} members will be moved into your {0} as well.";
            public const string AddFamilyMember = "Would you like to <a href=\"{0}\">add a family member</a>?";
            public const string AddUsername = "Add username";
            public const string AllChallenges = "All Challenges";
            public const string AllParticipatingLibraries = "All Participating Libraries";
            public const string AllPrograms = "All Age Groups";
            public const string AndOtherActivities = "and other activities";
            public const string AndTheir = "and their {0}";
            public const string Apply = "Apply";
            public const string AvatarLayerAltText = "View {0} options";
            public const string AvatarLayerBundleAltText = "View bundle options";
            public const string AvatarBundleAltText = "This badge was awarded when you unlocked the avatar bundle: {0}";
            public const string AvatarSaved = "Avatar saved.";
            public const string Back = "Back";
            public const string BackTo = "Back to {0}";
            public const string BackToChallenges = "Back to Challenges";
            public const string BackToEventsCommunityExperiences = "Back to Events & Community Experiences";
            public const string BackToMailbox = "Back to Mailbox";
            public const string Badge = "Badge";
            public const string BadgeDetails = "Badge Details";
            public const string Badges = "Badges";
            public const string BookList = "Book List";
            public const string Bundle = "Bundle";
            public const string Cancel = "Cancel";
            public const string Certificates = "Certificates";
            public const string ChangePassword = "Change Password";
            public const string ChooseAnOption = "Choose an option:";
            public const string Clear = "Clear";
            public const string CloseDialog = "Close dialog.";
            public const string CommunityExperiences = "Community Experiences";
            public const string Completed = "Completed!";
            public const string Confirm = "Confirm";
            public const string CouldNotCreate = "Could not create {0}: {1}";
            public const string CouldNotRemove = "Could not remove {0}: {1}";
            public const string CouldNotUpdate = "Could not update {0}: {1}.";
            public const string DateAtTime = "{0} at {1}";
            public const string Delete = "Delete";
            public const string DeleteMail = "Are you sure you wish to delete this mail: {0}";
            public const string Details = "Details";
            public const string Distance = "Distance";
            public const string DonateBook = "Donate book";
            public const string DonateYourBook = "Donate your book";
            public const string Download = "Download";
            public const string DownloadToShare = "Download to Share";
            public const string EmailDefaultFooter = "You are receiving this email because you are subscribed for updates from {{Sitename}}. You can [instantly unsubscribe at any time]({{UnsubscribeLink}})";
            public const string EnterAddressOrZipCode = "Enter an address or ZIP code";
            public const string EnterChallengeSearch = "Enter text to search for a challenge here";
            public const string EnterEventSearch = "Enter text to search for an event here";
            public const string EventHasEnded = "This streaming event has ended.";
            public const string EventNotFound = "Could not find the requested event.";
            public const string EventNotStarted = "This streaming event has not started yet.";
            public const string Events = "Events";
            public const string Explore = "Explore {0}";
            public const string Family = "Family";
            public const string FeaturedChallengeGroups = "Featured Challenge Groups";
            public const string Find = "Find";
            public const string FreeBookCode = "Free book code";
            public const string FreeBookCongratulations = "Congratulations, you've earned a free book!";
            public const string Group = "Group";
            public const string History = "History";
            public const string Joined = "Joined {0}!";
            public const string MailReplyPrefix = "Re: {0}";
            public const string MailSent = "Mail sent: {0}";
            public const string MoreInformation = "More information";
            public const string MyFavorites = "My Favorites";
            public const string Name = "Name";
            public const string NeedToChange = "Need to change your {0}? Use the mail icon at the top of the screen to contact us.";
            public const string NewMail = "New Mail!";
            public const string No = "No";
            public const string NoChallenges = "No Challenges";
            public const string NoEvents = "No Events";
            public const string NoMail = "You currently have no mail.";
            public const string NotStreamingYet = "Not streaming yet";
            public const string Optional = "Optional";
            public const string PasswordChanged = "Your password has been changed.";
            public const string PersonalPointGoalDescription = "A personal goal beyond the program default goal of {0} points.";
            public const string PersonalPointGoalLabel = "Points I will earn";
            public const string PointsYoullEarn = "Points you'll earn";
            public const string Prizes = "Prizes";
            public const string ProfileUpdated = "Profile updated.";
            public const string ProgramIsOver = "Program is over";
            public const string Progress = "Progress";
            public const string Read = "Read";
            public const string ReceiveEAudiobook = "Receive an e-audiobook";
            public const string RedeemCode = "Redeem code";
            public const string RedeemYourCode = "Redeem your code";
            public const string RelatedChallenge = "Related Challenge";
            public const string RelatedChallenges = "Related Challenges";
            public const string RemovedItem = "Removed: {0}";
            public const string Reply = "Reply";
            public const string ReplyTo = "Reply to:";
            public const string ReturnToTop = "Return to Top";
            public const string Save = "Save";
            public const string SaveMyFavorites = "Save My Favorites";
            public const string Search = "Search";
            public const string SecretCodeApplied = "Secret code applied!";
            public const string SeeItemsUnlocked = "See the items you unlocked.";
            public const string SelectABundle = "Select a Bundle";
            public const string SendMail = "Send Mail";
            public const string SendReply = "Send Reply";
            public const string SentOn = "Sent to you on {0}";
            public const string Share = "Share";
            public const string SignedInAs = "You are now signed in as {0}.";
            public const string SignInForStreams = "Sign in to access streaming programs!";
            public const string SignInToStream = "Sign in to stream!";
            public const string Status = "Status";
            public const string Stream = "Stream";
            public const string StreamingEnds = "Streaming ends: {0}";
            public const string StreamingEvents = "Streaming Events";
            public const string StreamNow = "Stream Now!";
            public const string StreamStarts = "Stream starts";
            public const string Subject = "Subject: {0}";
            public const string SwitchTo = "Switch To";
            public const string TotalPoints = "Total Points";
            public const string Unsubscribed = "You are now unsubscribed and will not receive any more emails from {0}.";
            public const string UpdatedItem = "Updated: {0}";
            public const string UpgradeToGroup = "Upgrade to Group";
            public const string UseMyZipCode = "Use my ZIP code";
            public const string ViewAll = "View All";
            public const string ViewCertificate = "View Certificate";
            public const string ViewCompleted = "View Completed";
            public const string ViewUncompleted = "View Uncompleted";
            public const string What = "What";
            public const string When = "When";
            public const string Where = "Where";
            public const string Yes = "Yes";
        }

        public static class Required
        {
            public const string EmailForSubscription = "To receive email updates please supply an email address to send them to.";
            public const string GroupName = "Group name is required.";
            public const string JavaScriptWarning = "This website relies on JavaScript. Please enable JavaScript in your browser to get the best experience.";
            public const string Missing = "Required fields are blank.";
            public const string MustEnterAmount = "You must enter an amount.";
            public const string SecretCode = "You must enter a code!";
            public const string SelectFirst = "Please select some participants first.";
        }

        public static class Title
        {
            public const string Activity = "Activity";
            public const string Avatar = "Avatar";
            public const string Badge = "Badge";
            public const string BookCode = "Book Code";
            public const string BundleItems = "Bundle Items";
            public const string Certificate = "Certificate";
            public const string ChallengeDetails = "Challenge: {0}";
            public const string ChallengeGroup = "Challenge Group: {0}";
            public const string Challenges = "Challenges";
            public const string CommunityExperiences = "Community Experiences";
            public const string Date = "Date";
            public const string DeleteBook = "Delete Book";
            public const string DeleteMail = "Delete Mail";
            public const string EditBook = "Edit Book";
            public const string Events = "Events";
            public const string EventsAndCommunityExperiences = "Events & Community Experiences";
            public const string ForgotPassword = "Forgot Password";
            public const string Join = "Join";
            public const string JoinNow = "{0} - Join Now!";
            public const string PageNotFound = "Page not found";
            public const string Participant = "Participant";
            public const string Points = "Points";
            public const string RegistrationOpens = "{0} - registration opens {1}";
            public const string SeeYouSoon = "{0} - See you soon!";
            public const string SendMail = "Send Mail";
            public const string ShareYourAvatar = "Share Your Avatar";
            public const string SignIn = "Sign in";
            public const string SignInTo = "Sign in to {0}";
            public const string StreamingEvents = "Streaming Events";
            public const string Subject = "Subject";
            public const string UpdateGroupDetails = "Update Group details";
            public const string UpgradeToGroup = "Upgrade from Family to Group";
            public const string UsernameRecovery = "Username Recovery";
        }

        public static class Validate
        {
            public const string AssociatedEmailAddressInvalid = "The email address associated with username {0} is invalid, please call or stop by to resolve this.";
            public const string AuthorizationCodeWarning = "To activate an authorization code, please sign in or <a href=\"{0}\">join</a>.";
            public const string BookTitle = "When providing an author of a book, please also provide a title.";
            public const string Branch = "The branch you've selected is not valid, please select another branch.";
            public const string CodeAlready = "All selected participants already have that Secret Code.";
            public const string CouldNotCreate = "Could not create your account: {0}";
            public const string CouldNotFavorite = "One or more of the selected {0} could not be favorited.";
            public const string CouldNotLog = "Sorry, we couldn't log your activity: {0}";
            public const string CouldNotRecover = "Could not recover username(s): {0}";
            public const string CouldNotSaveAvatar = "Couldn't save your avatar, sorry!";
            public const string CouldNotSaveAvatarReason = "Could not save avatar: {0}";
            public const string CustomizeAvatarFirst = "Please customize your avatar and save it, then you can share it!";
            public const string Email = "The {0} field is not a valid e-mail address.";
            public const string EmailAddressInvalid = "The email address {0} is invalid.";
            public const string EmailConfigured = "Username '{0}' does not have an email address configured.";
            public const string EmailPhoneNeededForPrizes = "Email and Phone Number are not required however at least one is needed in order to be eligible for prizes.";
            public const string EmailSubscription = "Please let us know if you would like to receive emails throughout the program.";
            public const string FirstTime = "Please let us know if this is your first time participating in the program.";
            public const string NotOpen = "The program is not accepting registrations at this time.";
            public const string NotOpenActivity = "The program is not open for activity at this time.";
            public const string NotOpenSignins = "The program is not accepting sign-ins at this time.";
            public const string ParticipantQuestionnaire = "Activity cannot be logged for this participant until they log in and answer a questionnaire.";
            public const string Password = "The provided password is incorrect.";
            public const string PasswordIssue = "Please correct the issues with your password.";
            public const string PasswordLength = "The password you've provided is too short, it must be at least {0} characters long.";
            public const string PasswordRequirement = "Your password must be at least 6 characters long and include a number.";
            public const string PasswordRequiresDigit = "You must include a number in your password.";
            public const string PasswordRequiresLowercase = "You must include a lowercase letter in your password.";
            public const string PasswordRequiresSymbol = "You must include a special character in your password.";
            public const string PasswordRequiresUppercase = "You must include an uppercase letter in your password.";
            public const string PasswordsMatch = "Password and password confirmation do not match.";
            public const string Permission = "Permission denied.";
            public const string Phone = "The {0} field is not a valid phone number.";
            public const string Program = "The age group you've selected is not valid, please select another age group.";
            public const string School = "The school you've selected is not valid, please select another school.";
            public const string SessionExpired = "Your session has expired. Please sign in again.";
            public const string SomethingWentWrong = "Something went wrong, please send us a mail with details of what you were attempting to do.";
            public const string System = "The system you've selected is not valid, please select another system.";
            public const string Token = "Password reset token '{0}' is not valid, please start the password reset process over.";
            public const string TokenExpired = "Password reset token '{0}' has expired, please start the password reset process over.";
            public const string UnableToAdd = "Unable to add: {0}";
            public const string UnableToChangePassword = "Unable to change your password: {0}";
            public const string UnableToReset = "Unable to reset password: {0}";
            public const string Username = "Could not find username '{0}'.";
            public const string UsernamePasswordMismatch = "The username and password entered do not match.";
            public const string UsernameTaken = "Someone has already chosen that username, please try another.";
            public const string WholeNumber = "Please enter a whole number greater than 0.";
        }
    }
}
