<%@ Page Language="C#" MasterPageFile="~/ControlRoom/Control.Master" 
    AutoEventWireup="true" CodeBehind="SurveyEmbedCode.aspx.cs" Inherits="GRA.SRP.ControlRoom.Modules.Setup.SurveyEmbedCode" 
    ValidateRequest="false"
%>
<%@ Import Namespace="GRA.SRP.DAL" %>
<%@ Import Namespace="GRA.SRP.Utilities.CoreClasses" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<table width="100%"  style="border:double 3px #A3C0E8;">
<tr>
    <th class="style2" colspan=2>This screen will help you generate the appropriate HTML tags to insert in a badge message or notification, and perhaps in other configurable HTML areas
    so that the user will be able to take a surver you have created.  This is advanced functionality and requires some minimal knowldge of HTML coding concepts. 
    <hr />
    </th>

</tr>
<tr>
    <th class="style2" style="width: 50%"><b>Test/Survey: </b></th>
    <th style="width: 50%">&nbsp;</th>
</tr>
<tr>
    <td class="style2">
        <asp:DropDownList ID="SID" runat="server" DataSourceID="odsDDSurveys" 
            DataTextField="Name" DataValueField="SID" 
            AppendDataBoundItems="True"  Width="97%" AutoPostBack="False"
            >
            <asp:ListItem Value="0" Text="[Select a Test/Survey]"></asp:ListItem>
        </asp:DropDownList>
    </td>
    <td>
    </td>

</tr>
<tr>
    <th class="style2"><b>What type of item will the survey be generated by:  </b></th>
    <th>IFrame Width:</th>
</tr>
<tr>
    <td>
        <asp:DropDownList ID="DDSourceType" runat="server" 
            AppendDataBoundItems="True"  Width="97%" AutoPostBack="True" onselectedindexchanged="DDSourceType_SelectedIndexChanged"
            >
            <asp:ListItem Value="0" Text="[Select a 'Source']"></asp:ListItem>
            <asp:ListItem Value="3" Text="Game" ></asp:ListItem>
            <asp:ListItem Value="4" Text="Challenge"></asp:ListItem>
            <asp:ListItem Value="5" Text="Event"></asp:ListItem>
        </asp:DropDownList>        
    </td>
    <td>
        <asp:TextBox ID="IWidth" runat="server" Text='700' 
                    ReadOnly="False" Width="50px" CssClass="align-right"></asp:TextBox>
            <asp:RegularExpressionValidator id="revIWidth"
                ControlToValidate="IWidth"
                ValidationExpression="\d+"
                Display="Dynamic"
                EnableClientScript="true"
                ErrorMessage="<font color='red'>Width must be numeric.</font>"
                runat="server"
                Font-Bold="True" Font-Italic="True" 
                Text="<font color='red'> * Width must be numeric. </font>" 
                EnableTheming="True" 
                SetFocusOnError="True" />      
            <asp:RangeValidator ID="rvIWidth"
                ControlToValidate="IWidth"
                MinimumValue="0"
                MaximumValue="999"
                Display="Dynamic"
                Type="Integer"
                EnableClientScript="true"
                ErrorMessage="<font color='red'>Width must be from 0 to 999!</font>"
                runat="server" 
                Font-Bold="True" Font-Italic="True" 
                Text="<font color='red'> * Width must be from 0 to 999! </font>" 
                EnableTheming="True" 
                SetFocusOnError="True" />
        
        
    </td>
</tr>
<tr>
    <th class="style2">
        The name of the item the survey will be about:</th>
    <th>
        <b>IFrame Height:</b></th>
</tr>
<tr>
    <td class="style2">
        <asp:DropDownList ID="DDSourceID" runat="server" 
            AppendDataBoundItems="True"  Width="97%"
            >
        </asp:DropDownList>
     </td>
    <td>
        <asp:TextBox ID="IHeight" runat="server" Text='800' 
                    ReadOnly="False" Width="50px" CssClass="align-right"></asp:TextBox>
            <asp:RegularExpressionValidator id="RegularExpressionValidator1"
                ControlToValidate="IHeight"
                ValidationExpression="\d+"
                Display="Dynamic"
                EnableClientScript="true"
                ErrorMessage="<font color='red'>Width must be numeric.</font>"
                runat="server"
                Font-Bold="True" Font-Italic="True" 
                Text="<font color='red'> * Width must be numeric. </font>" 
                EnableTheming="True" 
                SetFocusOnError="True" />      
            <asp:RangeValidator ID="RangeValidator1"
                ControlToValidate="IHeight"
                MinimumValue="0"
                MaximumValue="9999"
                Display="Dynamic"
                Type="Integer"
                EnableClientScript="true"
                ErrorMessage="<font color='red'>Width must be from 0 to 9999!</font>"
                runat="server" 
                Font-Bold="True" Font-Italic="True" 
                Text="<font color='red'> * Width must be from 0 to 9999! </font>" 
                EnableTheming="True" 
                SetFocusOnError="True" />        
        
    </td>
</tr>
    
<tr>
    <td class="style2">
        &nbsp;
        <asp:Button ID="btnFilter" runat="server" Text="Generate" CausesValidation="true"
        Width="150px" CSSClass="btn-lg btn-green" onclick="btnFilter_Click"/>

 
        &nbsp;&nbsp;
        <asp:Button ID="btnFilter0" runat="server" Text="Clear" CausesValidation="false"
        Width="150px" CSSClass="btn-lg btn-gray" onclick="btnFilter0_Click" />

 
        </td>
</tr>


    



    
</table>



	<asp:ObjectDataSource ID="odsDDSurveys" runat="server" 
        SelectMethod="GetAll" 
        TypeName="GRA.SRP.DAL.Survey">
	</asp:ObjectDataSource>


    <asp:Panel ID="pnlResults" runat="server" Visible="False">
        <br />
        <asp:Label ID="lblInfo" runat="server" Font-Size="Large" ForeColor="#CC0000"></asp:Label>
        <hr />
        <br />
        <asp:TextBox ID="txtResults" runat="server" TextMode="MultiLine" Rows="10" Width="98%"></asp:TextBox>
<table width="100%" border=0>


</table>





    </asp:Panel>

</asp:Content>