# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Great Reading Adventure
subtitle: "Reimagining Summer Reading"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Adventures, secret codes, challenges, and badges await! Take your literacy program online with
  free, open source software developed by libraries, for libraries.
github_username: MCLD
minimal_mistakes_skin: default
locale: "en-US"
search: true
repository: "mcld/gra-site-test"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Phoenix # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

og_image: "/assets/images/great-reading-adventure.png"

author:
  avatar: "/assets/images/great-reading-adventure.png"
  links:
    - label: "Latest Release"
      icon: "fas fa-fw fa-download"
      url: "https://github.com/MCLD/greatreadingadventure/releases/latest"
    - label: "Demo"
      icon: "fas fa-fw fa-laptop-code"
      url: "http://demo.greatreadingadventure.com/"
    - label: "Manual"
      icon: "fas fa-fw fa-book"
      url: "https://manual.greatreadingadventure.com/"
    - label: "Discussions"
      icon: "fas fa-fw fa-comments"
      url: "https://github.com/MCLD/greatreadingadventure/discussions"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MCLD/greatreadingadventure/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-58128527-1"
    anonymize_ip: true

footer:
  links:
    - label: "Latest Release"
      icon: "fas fa-fw fa-download"
      url: "https://github.com/MCLD/greatreadingadventure/releases/latest"
    - label: "Demo"
      icon: "fas fa-fw fa-laptop-code"
      url: "http://demo.greatreadingadventure.com/"
    - label: "Manual"
      icon: "fas fa-fw fa-book"
      url: "https://manual.greatreadingadventure.com/"
    - label: "Discussions"
      icon: "fas fa-fw fa-comments"
      url: "https://github.com/MCLD/greatreadingadventure/discussions"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MCLD/greatreadingadventure/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
