//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRA.SRP.ControlRoom {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SRPResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRPResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRA.SRP.ControlRoom.SRPResources", typeof(SRPResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record added successfully..
        /// </summary>
        public static string AddedOK {
            get {
                return ResourceManager.GetString("AddedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. {0}.
        /// </summary>
        public static string ApplicationError1 {
            get {
                return ResourceManager.GetString("ApplicationError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password.
        /// </summary>
        public static string BadUserPass {
            get {
                return ResourceManager.GetString("BadUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Reading Adventure - Control Room.
        /// </summary>
        public static string CRTitle {
            get {
                return ResourceManager.GetString("CRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully..
        /// </summary>
        public static string DeleteOK {
            get {
                return ResourceManager.GetString("DeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Room Login.
        /// </summary>
        public static string LoginGroup {
            get {
                return ResourceManager.GetString("LoginGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been emailed to your email address..
        /// </summary>
        public static string PasswordEmailed {
            get {
                return ResourceManager.GetString("PasswordEmailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset request.
        /// </summary>
        public static string PasswordEmailSubject {
            get {
                return ResourceManager.GetString("PasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset!.
        /// </summary>
        public static string PasswordEmailSuccessSubject {
            get {
                return ResourceManager.GetString("PasswordEmailSuccessSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required;.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Reading Adventure Control Room.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records refreshed from database successfully..
        /// </summary>
        public static string RefreshAllOK {
            get {
                return ResourceManager.GetString("RefreshAllOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record refreshed from database successfully..
        /// </summary>
        public static string RefreshOK {
            get {
                return ResourceManager.GetString("RefreshOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records saved successfully..
        /// </summary>
        public static string SaveAllOK {
            get {
                return ResourceManager.GetString("SaveAllOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record saved successfully..
        /// </summary>
        public static string SaveOK {
            get {
                return ResourceManager.GetString("SaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? Click here!.
        /// </summary>
        public static string UserAccountRecovery {
            get {
                return ResourceManager.GetString("UserAccountRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
