name: Build Docker image

on: [push, pull_request]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Docker image name
      run: echo "BLD_DOCKER_IMAGE=$(echo $GITHUB_REPOSITORY/${PWD##*/}
        | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Extract Docker username
      run: echo "BLD_DOCKER_USERNAME=$(echo $GITHUB_REPOSITORY 
        | cut -d/ -f1
        | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Run docker-build.bash
      env:
        BLD_DOCKER_HOST: docker.pkg.github.com
        BLD_DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: ./docker-build.bash
