name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Docker image name
      run: echo ::set-env name=BLD_DOCKER_IMAGE::$(echo $GITHUB_REPOSITORY/${PWD##*/}
        | tr '[:upper:]' '[:lower:]')

    - name: Extract Docker username
      run: echo ::set-env name=BLD_DOCKER_USERNAME::$(echo $GITHUB_REPOSITORY 
        | cut -d/ -f1
        | tr '[:upper:]' '[:lower:]')

    - name: Run docker-build.bash
      env:
        BLD_DOCKER_HOST: docker.pkg.github.com
        BLD_DOCKER_PASSWORD: ${{secrets.GITHUB_TOKEN}}
      run: ./docker-build.bash

